# Generated by Django 4.1.5 on 2023-01-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Термин', 'verbose_name_plural': 'Термины'},
        ),
    ]
